### ISSUE TITLE
Can't get the mnist example working

### ISSUE THREAD

**Issue by rbunn80110** [greydanus/excitationbp#4]
Not sure what to make of this error.  I haven't changed anything in the code.    

np_loss = loss.data.numpy()[0]
IndexError: too many indices for array

**Comment by greydanus** [comment]
I just added some substantial updates this morning. Before anything else, can you confirm that you are using the latest PyTorch? It looks like loss.data.numpy() might be returning a float

**Comment by rbunn80110** [comment]
Yes, I compiled the latest master branch of PyTorch a few hours ago and downloaded the latest code.  I'm pretty confident there are errors in the MNIST example.  

By changing this line:
np_loss = loss.data.numpy()[0]

to this:
np_loss = float(loss.data.numpy())

I was able to get to a point where the basic EB plot appears, however then I hit more errors after that.  You may want to try running this code on your end to see the issues. (perhaps compile the latest master branch of PyTorch when testing)  This is really great work, which is why I'm trying to help testing it so I can better understand how everything works.  I really appreciate you taking your time to put this up on github.

**Comment by greydanus** [comment]
Thanks, I’m glad you find it useful. This error is confusing because I just ran all the latest code in this repo on my laptop today. Tomorrow I’ll look for a better fix. I may end up hosting the tutorials in colab notebooks, if colab lets me

**Comment by rbunn80110** [comment]
Everything appears to work just fine if you use the latest version of pytorch on conda 0.3.1  You have 0.4 listed under dependencies on the main page which as far as I can tell doesn't exist yet.  So basically the problem was I compiled pytorch from source which appears to have been incompatible in some ways.

**Comment by greydanus** [comment]
fixed readme
