### ISSUE TITLE
compatible with the newest version?

### ISSUE THREAD

**Issue by donhk1011** [greydanus/excitationbp#7]
Hi,

Is it compatible with the newest version?

If not, how I could make it work? I tried 0.4.0 but it didnt work.

I looked into the code of eb_convND.py. It looks very complicated and I don't know what to do first.

Could you please help me?

Thanks,

**Comment by donhk1011** [comment]
In addition, I think the current implementation is not compatible with cuda. How can I modify it to use cuda?

**Comment by greydanus** [comment]
Hey donhk1011,

I'm not actively supporting this repo any more. It is not compatible with pytorch 0.4, but it is compatible with v0.3. My suggestion is to run the tutorials in v0.3, understand what my code is doing, and then try to port to v0.4/cuda yourself.
